version: '3.6'
services:

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hasura

  graphql-engine:
    build:
      context: .
      dockerfile: ./hasura/Dockerfile.console
    restart: always
    volumes:
      - ./hasura:/hasura
    ports:
      - "8080:8080"
      - "9693:9693"
      - "9695:9695"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup          # http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 60
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      #HASURA_GRAPHQL_ADMIN_SECRET: "myadminsecretkey"   # not needed for dev env
      #HASURA_GRAPHQL_JWT_SECRET: ""                     # see hasura/notes.md
    depends_on:
      - "postgres"

  next-app:
    image: node:12.6.0
    command: sh -c 'npm install && npm run start'
    working_dir: /app
    restart: always
    ports:
      - "8081:8081"
      - "9229:9229"
    volumes:
      - ./app:/app
    environment:
      PORT: "8081"
